-- 创建限制配置表
CREATE TABLE STOCK_LIMITATION
(
    LIMIT_NAME NVARCHAR2(50) PRIMARY KEY NOT NULL,
    LIMIT_AMOUNT NUMBER NOT NULL,
    LIMIT_INVESTORS NUMBER NOT NULL
);

-- 创建控制列表
CREATE TABLE STOCK_CTRL_LIST
(
  REQUEST_NO NVARCHAR2(24) PRIMARY KEY NOT NULL,
  BALANCE NUMBER NOT NULL,
  TRADE_ACCO NVARCHAR2(17) NOT NULL,
  STOCK_CODE NVARCHAR2(6) NOT NULL,
  BIZ_CODE NVARCHAR2(3) NOT NULL,
  REQUEST_DATE TIMESTAMP
);
CREATE INDEX INDEX_TRADE_ACCO ON STOCK_CTRL_LIST(TRADE_ACCO);