

alter table stock_limitation drop constraint CHECK_LIMATATION_AMOUNT;

ALTER TABLE STOCK_LIMITATION ADD CONSTRAINT CHECK_LIMATATION_AMOUNT CHECK (CURRENT_AMOUNT <= LIMIT_AMOUNT and CURRENT_AMOUNT >= 0);
ALTER TABLE STOCK_LIMITATION ADD CONSTRAINT CHECK_LIMATATION_INVESTORS CHECK (CURRENT_INVESTORS <= LIMIT_INVESTORS and CURRENT_INVESTORS >=0);


